# Top-7 ranking datasets. Scores are editorial (see /how-we-rank/). Fees/figures are indicative —
# providers change them; the page footer tells readers to verify on the provider site.
M7 = ["Security", "Fees", "Ease of use", "Assets", "Features", "Support", "Reputation"]

LISTS = {
 "exchanges": {
  "title": "Top 7 Crypto Exchanges",
  "h1": "Top 7 Crypto Exchanges (2026)",
  "desc": "The seven best crypto exchanges for beginners, low fees, US users and advanced traders — scored on security, fees, assets and more.",
  "intro": "We scored 24 exchanges on seven metrics and kept the seven that matter. Every pick below is a regulated or long-established venue with proof-of-reserves or audited custody. Fees are spot taker fees at the base tier.",
  "cols": ["Score", "Taker fee", "Coins", "US availability", "Best for"],
  "items": [
   {"name":"Coinbase","key":"coinbase","badge":"Best for beginners","score":9.1,"fee":"0.60%","coins":"250+","us":"Yes (all states)","bestfor":"First purchase, simplicity",
    "m":[10,6,10,8,8,9,10],"pros":["Publicly listed (NASDAQ: COIN), heavily regulated","Cleanest onboarding of any exchange","Insured USD balances, strong account security"],"cons":["Highest base fees on this list","Advanced mode needed for lower fees"],
    "choose":"you want the safest first purchase and don't mind paying for simplicity.","skip":"you trade often — fees compound fast."},
   {"name":"Kraken","key":"kraken","badge":"Most trusted","score":9.0,"fee":"0.40%","coins":"300+","us":"Yes (most states)","bestfor":"Security-first holders, staking",
    "m":[10,8,8,8,9,10,10],"pros":["Never hacked since 2011; regular proof-of-reserves","24/7 live chat support","Competitive Pro fees from 0.25% taker"],"cons":["Interface less polished than Coinbase","Some products unavailable in a few US states"],
    "choose":"you value a security track record over a flashy app.","skip":"you need the absolute lowest fees."},
   {"name":"Binance","key":"binance","badge":"Lowest fees","score":8.7,"fee":"0.10%","coins":"400+","us":"No (Binance.US separate)","bestfor":"Global users, altcoins, derivatives",
    "m":[8,10,7,10,10,8,8],"pros":["0.10% base fee, lower with BNB","Deepest liquidity and widest altcoin list","Earn, launchpool and futures under one roof"],"cons":["Not available to US residents","Regulatory history in several jurisdictions"],
    "choose":"you're outside the US and want maximum assets at minimum fees.","skip":"you are a US resident or want a simple app."},
   {"name":"Bybit","key":"bybit","badge":"Best for derivatives","score":8.4,"fee":"0.10%","coins":"600+","us":"No","bestfor":"Futures, copy trading",
    "m":[8,9,8,10,10,8,7],"pros":["Top-3 derivatives liquidity","Unified trading account and copy trading","Fast listings of new tokens"],"cons":["Not for US users","Aggressive bonus marketing can distract beginners"],
    "choose":"you trade perpetuals or want copy trading.","skip":"you're a buy-and-hold beginner."},
   {"name":"OKX","key":"okx","badge":"Best all-rounder (ex-US)","score":8.3,"fee":"0.10%","coins":"350+","us":"No","bestfor":"Web3 wallet + exchange combo",
    "m":[8,9,8,9,10,8,8],"pros":["Built-in Web3 wallet with DEX aggregation","Monthly proof-of-reserves","Strong mobile app"],"cons":["Not available in the US","Product breadth can overwhelm new users"],
    "choose":"you want CEX and self-custody in one app.","skip":"you want the simplest possible experience."},
   {"name":"Crypto.com","key":"cryptocom","badge":"Best for cards & rewards","score":8.0,"fee":"0.25%","coins":"350+","us":"Yes","bestfor":"Visa card cashback, mobile-first users",
    "m":[8,7,9,9,8,7,8],"pros":["Visa card with crypto cashback","Available in the US with a polished app","Wide fiat on-ramps"],"cons":["Card perks require locking CRO","Spread on the app's simple buy is high"],
    "choose":"you want to spend crypto with a card.","skip":"you dislike token-locking requirements."},
   {"name":"Bitget","key":"bitget","badge":"Best for copy trading","score":7.8,"fee":"0.10%","coins":"800+","us":"No","bestfor":"Copy trading, new listings",
    "m":[7,9,8,10,9,7,7],"pros":["Largest copy-trading community","Very broad altcoin coverage","Protection fund publicly tracked"],"cons":["Not available in the US","Younger brand than the others"],
    "choose":"you want to mirror proven traders.","skip":"you need deep regulatory pedigree."}
  ],
  "faq":[["Which exchange is best for beginners?","Coinbase for US users and Binance for most other countries: both have guided buy flows, bank transfers and strong account security. Pay the slightly higher fee while you learn, then move to Advanced/Pro modes."],
         ["Should I keep coins on the exchange?","Keep only what you actively trade. Move long-term holdings to a hardware wallet — see our Top 7 Wallets."],
         ["How did you score these?","Seven metrics, each 0–10, weighted equally: security, fees, ease of use, assets, features, support and reputation. Read /how-we-rank/."]]
 },
 "wallets": {
  "title":"Top 7 Crypto Wallets","h1":"Top 7 Crypto Wallets (2026)",
  "desc":"Best hardware and software wallets for self-custody, DeFi and everyday use — scored on security, usability and chain support.",
  "intro":"Not your keys, not your coins. We tested hardware and software wallets on seven metrics. Hardware wallets win on security; software wallets win on convenience — most people need one of each.",
  "cols":["Score","Type","Price","Chains","Best for"],
  "items":[
   {"name":"Ledger","key":"ledger","badge":"Best overall","score":9.2,"fee":"Hardware","coins":"$79–$279","us":"5,500+ assets","bestfor":"Long-term holders",
    "m":[10,8,8,10,9,8,10],"pros":["Secure Element chip, most-sold hardware wallet","Ledger Live covers buying, staking and swaps","Supports nearly every chain"],"cons":["Closed-source firmware","Premium models are pricey"],"choose":"you hold more than you'd be comfortable losing.","skip":"you only hold small amounts on one chain."},
   {"name":"Trezor","key":"trezor","badge":"Best open-source","score":9.0,"fee":"Hardware","coins":"$49–$219","us":"1,000+ assets","bestfor":"Open-source purists",
    "m":[10,9,8,8,8,8,10],"pros":["Fully open-source hardware and software","Trezor Suite is clean and privacy-focused","Safe 3/5 now include Secure Element"],"cons":["Fewer chains than Ledger","No Bluetooth models"],"choose":"you want auditable security.","skip":"you need broad altcoin coverage."},
   {"name":"Tangem","key":"tangem","badge":"Easiest hardware","score":8.6,"fee":"Hardware (card)","coins":"$55–$70","us":"Multi-chain","bestfor":"Beginners, gifting",
    "m":[9,9,10,8,7,8,8],"pros":["Credit-card form factor, NFC tap to sign","No seed phrase needed (optional backup cards)","25-year warranty"],"cons":["Requires a phone with NFC","Smaller app ecosystem"],"choose":"you want hardware security without the gadget.","skip":"you want desktop-first workflows."},
   {"name":"MetaMask","key":"metamask","badge":"Best for Ethereum & L2s","score":8.4,"fee":"Software (free)","coins":"Free","us":"EVM chains","bestfor":"DeFi, NFTs",
    "m":[7,8,8,8,10,7,10],"pros":["The default wallet for Ethereum dApps","Pairs with Ledger/Trezor","Built-in swaps, bridges and portfolio"],"cons":["Hot wallet — phishing target","Swap fees are not the cheapest"],"choose":"you use Ethereum DeFi or NFTs.","skip":"you mainly hold Bitcoin."},
   {"name":"Rabby","key":"rabby","badge":"Best for DeFi power users","score":8.3,"fee":"Software (free)","coins":"Free","us":"EVM chains","bestfor":"Transaction simulation",
    "m":[8,9,7,8,10,7,8],"pros":["Simulates every transaction before signing","Automatic chain switching","Hardware-wallet support"],"cons":["Less known than MetaMask","Browser/desktop focus"],"choose":"you sign a lot of DeFi transactions.","skip":"you want the simplest mobile wallet."},
   {"name":"Phantom","key":"phantom","badge":"Best for Solana","score":8.2,"fee":"Software (free)","coins":"Free","us":"Solana, Ethereum, Bitcoin, Base","bestfor":"Solana users",
    "m":[8,9,10,7,8,7,8],"pros":["Best-in-class UX on mobile and desktop","Scam-site warnings and spam-NFT burning","Multi-chain since 2024"],"cons":["Hot wallet","Fewer chains than MetaMask"],"choose":"you live on Solana.","skip":"you need niche EVM chains."},
   {"name":"Trust Wallet","key":"trustwallet","badge":"Best mobile multi-chain","score":7.9,"fee":"Software (free)","coins":"Free","us":"100+ chains","bestfor":"Mobile-first users",
    "m":[7,9,9,10,8,7,8],"pros":["Supports 100+ chains and millions of assets","Simple mobile UX","Built-in dApp browser"],"cons":["Owned by Binance — governance questions","Hot wallet"],"choose":"you want everything in one mobile app.","skip":"you hold large balances — go hardware."}
  ],
  "faq":[["Hardware or software wallet?","Both. Software for daily use and DeFi; hardware for anything you'd regret losing. Pair them: MetaMask or Rabby can sign with a Ledger."],
         ["What is a seed phrase?","12–24 words that regenerate your keys. Write it on paper or steel, never in a photo or cloud note. Anyone with the phrase controls the coins."],
         ["Are free wallets safe?","The software is; the risk is you — phishing, fake sites, blind signing. Our Step 4 chapter covers the seven rules."]]
 },
 "layer-1": {
  "title":"Top 7 Layer-1 Blockchains","h1":"Top 7 Layer-1 Blockchains (2026)",
  "desc":"The seven base-layer blockchains that matter, ranked on security, decentralisation, ecosystem, throughput and adoption.",
  "intro":"A Layer-1 is a base chain that settles its own transactions. We rank them on security budget, decentralisation, developer ecosystem, throughput, fees, adoption and track record.",
  "cols":["Score","Consensus","Avg. fee","TPS (practical)","Best for"],
  "items":[
   {"name":"Bitcoin","key":"bitcoin","badge":"Most secure","score":9.4,"fee":"Proof of Work","coins":"$0.50–$5","us":"~7","bestfor":"Store of value",
    "m":[10,10,6,7,8,10,10],"pros":["Largest security budget of any network","Fixed 21M supply, 15+ years uptime","Spot ETFs and corporate treasuries"],"cons":["Slow, limited programmability","Fees spike in congestion"],"choose":"you want digital gold.","skip":"you want smart contracts on the base layer."},
   {"name":"Ethereum","key":"ethereum","badge":"Best ecosystem","score":9.3,"fee":"Proof of Stake","coins":"$0.20–$3","us":"~15–30 (L1)","bestfor":"DeFi, NFTs, settlement for L2s",
    "m":[10,9,8,9,10,9,10],"pros":["Largest developer and DeFi ecosystem","Rollup-centric roadmap scales via L2s","Staking yield from protocol"],"cons":["L1 fees still high at peak","Complexity for newcomers"],"choose":"you want the deepest app ecosystem.","skip":"you need sub-cent fees on L1 — use an L2."},
   {"name":"Solana","key":"solana","badge":"Fastest & cheapest","score":8.8,"fee":"Proof of Stake + PoH","coins":"<$0.01","us":"1,000s","bestfor":"Consumer apps, payments, DEX trading",
    "m":[8,7,9,10,10,8,8],"pros":["Sub-second, sub-cent transactions","Leading DEX volume and consumer apps","Firedancer client improves resilience"],"cons":["Past outages","Higher hardware requirements for validators"],"choose":"you want speed and cheap fees.","skip":"you prioritise maximum decentralisation."},
   {"name":"BNB Chain","key":"bnbchain","badge":"Best for low-cost EVM","score":7.9,"fee":"PoSA","coins":"~$0.03","us":"~2,000","bestfor":"Retail EVM apps",
    "m":[7,6,8,9,8,8,8],"pros":["EVM-compatible with very low fees","Huge retail user base via Binance","Fast block times"],"cons":["Limited validator set","Binance-centric"],"choose":"you want cheap EVM transactions.","skip":"decentralisation is your top criterion."},
   {"name":"Avalanche","key":"avalanche","badge":"Best for custom chains","score":7.7,"fee":"Snowman PoS","coins":"~$0.05","us":"~4,500","bestfor":"Enterprise subnets, gaming",
    "m":[8,8,7,8,9,7,8],"pros":["Subnets/L1s let apps run their own chains","Sub-2s finality","Institutional pilots"],"cons":["Fragmented liquidity across subnets","Smaller DeFi than Ethereum/Solana"],"choose":"you're building a dedicated app-chain.","skip":"you want the deepest liquidity."},
   {"name":"TON","key":"ton","badge":"Best distribution","score":7.5,"fee":"Proof of Stake","coins":"~$0.01","us":"High","bestfor":"Telegram mini-apps",
    "m":[7,6,9,10,8,7,7],"pros":["Native Telegram integration (900M+ users)","Mini-apps and tap-to-earn drove adoption","Very low fees"],"cons":["Concentrated early distribution","Ecosystem still maturing"],"choose":"you build for Telegram users.","skip":"you want battle-tested DeFi."},
   {"name":"Cardano","key":"cardano","badge":"Most research-driven","score":7.2,"fee":"Ouroboros PoS","coins":"~$0.15","us":"~250","bestfor":"Peer-reviewed design, staking",
    "m":[9,9,6,6,7,7,8],"pros":["Formal methods and peer-reviewed protocol","Highly decentralised staking","Low energy use"],"cons":["Slower ecosystem growth","Lower DeFi TVL"],"choose":"you prize methodical engineering.","skip":"you want the busiest app ecosystem."}
  ],
  "faq":[["What is a Layer-1 vs Layer-2?","A Layer-1 settles its own transactions and secures itself. A Layer-2 processes transactions off-chain and posts proofs/data to a Layer-1 for security — see our Top 7 Layer-2s."],
         ["Is ranking a blockchain even possible?","Only against stated criteria. Ours are published on /how-we-rank/; disagree with the weights and the order changes — that's the point of showing the metrics."]]
 },
 "layer-2": {
  "title":"Top 7 Layer-2 Networks","h1":"Top 7 Ethereum Layer-2 Networks (2026)",
  "desc":"The seven best Ethereum Layer-2 rollups ranked on security stage, fees, TVL, ecosystem and decentralisation.",
  "intro":"Layer-2s inherit Ethereum security while cutting fees 10–100×. We rank by L2BEAT-style maturity stage, fees, TVL, ecosystem and decentralisation of sequencers and proofs.",
  "cols":["Score","Type","Avg. fee","Stage","Best for"],
  "items":[
   {"name":"Arbitrum","key":"arbitrum","badge":"Best overall","score":9.0,"fee":"Optimistic rollup","coins":"~$0.01–0.05","us":"Stage 1","bestfor":"DeFi depth",
    "m":[9,9,9,10,9,8,9],"pros":["Largest L2 by TVL and DeFi activity","BoLD permissionless validation","Mature tooling and Orbit chains"],"cons":["7-day withdrawal window via native bridge","Centralised sequencer"],"choose":"you want the deepest L2 DeFi.","skip":"you need instant native withdrawals."},
   {"name":"Base","key":"base","badge":"Fastest growing","score":8.9,"fee":"OP Stack rollup","coins":"<$0.01","us":"Stage 1","bestfor":"Consumer apps, onboarding",
    "m":[8,10,10,9,9,9,9],"pros":["Coinbase distribution to 100M+ users","Lowest fees among major L2s","Explosive consumer and social-app growth"],"cons":["Coinbase-operated sequencer","Memecoin noise"],"choose":"you're onboarding newcomers.","skip":"you avoid corporate-run infrastructure."},
   {"name":"Optimism (OP Mainnet)","key":"optimism","badge":"Best for Superchain","score":8.5,"fee":"OP Stack rollup","coins":"~$0.01","us":"Stage 1","bestfor":"Superchain builders, public goods",
    "m":[8,9,8,8,9,8,9],"pros":["OP Stack powers Base, Soneium, Unichain and more","Fault proofs live","RetroPGF funds public goods"],"cons":["TVL below Arbitrum/Base","Governance complexity"],"choose":"you build on the OP Stack.","skip":"you only chase liquidity."},
   {"name":"zkSync Era","key":"zksync","badge":"Best ZK ecosystem","score":8.0,"fee":"ZK rollup","coins":"~$0.02","us":"Stage 0/1","bestfor":"ZK-native apps, elastic chains",
    "m":[9,8,7,7,9,7,8],"pros":["Validity proofs — no challenge window","Native account abstraction","Elastic chain network"],"cons":["Smaller DeFi than optimistic peers","Decentralisation still in progress"],"choose":"you want ZK security guarantees.","skip":"you need the largest liquidity pools."},
   {"name":"Polygon (PoS + zkEVM)","key":"polygon","badge":"Best for enterprises & payments","score":7.9,"fee":"Sidechain + ZK rollup","coins":"<$0.01","us":"Mixed","bestfor":"Brands, stablecoin payments",
    "m":[7,9,9,8,9,8,9],"pros":["Most enterprise and brand integrations","Very low fees on PoS","AggLayer vision unifies chains"],"cons":["PoS is a sidechain, not a rollup","zkEVM adoption modest"],"choose":"you need brand-friendly, cheap transactions.","skip":"you require strict rollup security."},
   {"name":"Starknet","key":"starknet","badge":"Most innovative tech","score":7.6,"fee":"ZK (STARK) rollup","coins":"~$0.01","us":"Stage 1","bestfor":"Cairo developers, gaming",
    "m":[9,8,6,6,9,7,8],"pros":["STARK proofs, no trusted setup","Native account abstraction","Fast fee reductions"],"cons":["Cairo language learning curve","Smaller ecosystem"],"choose":"you want cutting-edge cryptography.","skip":"you need Solidity compatibility."},
   {"name":"Scroll","key":"scroll","badge":"Best EVM-equivalent ZK","score":7.3,"fee":"ZK rollup (zkEVM)","coins":"~$0.02","us":"Stage 1","bestfor":"Solidity devs wanting ZK",
    "m":[8,8,7,6,8,7,7],"pros":["Bytecode-level EVM equivalence","Clean security model","Steady growth"],"cons":["Lower TVL","Fewer flagship apps"],"choose":"you want ZK without rewriting contracts.","skip":"you need the busiest chain."}
  ],
  "faq":[["Are L2s safe?","Safer than most alt-L1s because they post data to Ethereum, but each has upgrade keys and sequencer trust assumptions. Check its stage on L2BEAT before parking large sums."],
         ["How do I move funds to an L2?","Use the official bridge or withdraw directly from an exchange that supports the L2 (Coinbase → Base, Binance → Arbitrum). Our Step 6 chapter walks through it."]]
 },
 "defi": {
  "title":"Top 7 DeFi Platforms","h1":"Top 7 DeFi Platforms (2026)",
  "desc":"The seven most important DeFi protocols for lending, trading, staking and yield, scored on security record, TVL and usability.",
  "intro":"DeFi lets you lend, trade and earn without an intermediary. We rank by audit and exploit record, TVL, longevity, usability, chains supported, yields and governance.",
  "cols":["Score","Category","TVL tier","Chains","Best for"],
  "items":[
   {"name":"Aave","key":"aave","badge":"Best lending","score":9.2,"fee":"Lending","coins":"$20B+","us":"10+","bestfor":"Borrowing against crypto",
    "m":[10,8,9,10,10,8,10],"pros":["Largest lending protocol, battle-tested since 2017","GHO stablecoin and V4 roadmap","Multi-chain deployments"],"cons":["Liquidation risk if collateral drops","Variable rates"],"choose":"you want to borrow or earn on blue-chips.","skip":"you can't monitor your health factor."},
   {"name":"Uniswap","key":"uniswap","badge":"Best DEX","score":9.1,"fee":"DEX","coins":"$5B+","us":"12+","bestfor":"Token swaps",
    "m":[10,8,10,9,10,8,10],"pros":["Most-used DEX, never exploited at core","V4 hooks enable custom pools","Unichain L2"],"cons":["Slippage on thin pairs","LP impermanent loss"],"choose":"you swap tokens on EVM chains.","skip":"you want order-book trading."},
   {"name":"Lido","key":"lido","badge":"Best liquid staking","score":8.8,"fee":"Liquid staking","coins":"$25B+","us":"Ethereum","bestfor":"Earning ETH staking yield while staying liquid",
    "m":[9,8,10,8,8,8,9],"pros":["stETH is the most integrated LST","No 32 ETH minimum","Dual-governance adds safety"],"cons":["Concentration concerns on Ethereum","Smart-contract + slashing risk"],"choose":"you hold ETH long term.","skip":"you oppose staking concentration."},
   {"name":"Sky (MakerDAO)","key":"makerdao","badge":"Best stablecoin protocol","score":8.5,"fee":"Stablecoin / CDP","coins":"$8B+","us":"Ethereum + L2s","bestfor":"DAI/USDS savings rate",
    "m":[10,8,7,8,9,7,10],"pros":["Oldest DeFi protocol; survived 2020 and 2022","Savings rate on USDS/DAI","Real-world-asset backing"],"cons":["Rebrand confusion (Sky/USDS)","Governance complexity"],"choose":"you want yield on a decentralised stablecoin.","skip":"you want the simplest UX."},
   {"name":"Jupiter","key":"jupiter","badge":"Best on Solana","score":8.4,"fee":"DEX aggregator","coins":"$2B+","us":"Solana","bestfor":"Best-price swaps on Solana",
    "m":[8,9,10,8,10,8,8],"pros":["Routes across every Solana DEX","Limit orders, DCA and perps","Fast and cheap"],"cons":["Solana-only","Perps carry leverage risk"],"choose":"you trade on Solana.","skip":"you're EVM-only."},
   {"name":"Curve","key":"curve","badge":"Best for stablecoin swaps","score":8.0,"fee":"DEX","coins":"$2B+","us":"10+","bestfor":"Low-slippage stable and LST swaps",
    "m":[8,9,6,8,9,6,9],"pros":["Lowest slippage for like-kind assets","crvUSD and Llamalend","Deep stablecoin liquidity"],"cons":["Complex UI","2023 Vyper exploit history"],"choose":"you move size between stablecoins.","skip":"you're new to DeFi."},
   {"name":"Pendle","key":"pendle","badge":"Best yield trading","score":7.8,"fee":"Yield tokenisation","coins":"$4B+","us":"5+","bestfor":"Fixed yields, points farming",
    "m":[8,8,6,7,10,7,8],"pros":["Lock in fixed yields on-chain","Core venue for points/airdrop speculation","Multi-chain"],"cons":["Concepts (PT/YT) are advanced","Liquidity varies by market"],"choose":"you understand yield curves.","skip":"you want set-and-forget."}
  ],
  "faq":[["Is DeFi safe?","Protocols above have multi-year track records and audits, but smart-contract, oracle and governance risks never reach zero. Size positions accordingly and never approve unlimited allowances from a wallet holding your savings."],
         ["How do I start?","Finish Step 6 of our learning path, use Rabby or MetaMask with a hardware wallet, start on Arbitrum or Base with $50, and only use protocols on this list."]]
 },
 "cards": {
  "title":"Top 7 Crypto Cards","h1":"Top 7 Crypto Debit Cards (2026)",
  "desc":"The seven best crypto debit cards for cashback, availability and low fees — Visa/Mastercard cards that spend your crypto anywhere.",
  "intro":"Crypto cards convert coins at the point of sale. We rank on rewards, fees, availability, supported assets, app quality, limits and issuer reputation. Rewards tiers change often — verify before applying.",
  "cols":["Score","Network","Rewards (typ.)","Regions","Best for"],
  "items":[
   {"name":"Crypto.com Visa","key":"cryptocomcard","badge":"Best rewards ceiling","score":8.6,"fee":"Visa","coins":"0–5% CRO","us":"US, EU, UK, APAC","bestfor":"Users willing to stake CRO",
    "m":[8,7,9,9,10,7,8],"pros":["Up to 5% back plus streaming rebates on top tiers","Metal cards, wide availability","No annual fee"],"cons":["Best perks need large CRO lock-ups","Rewards cut several times historically"],"choose":"you'll lock CRO for perks.","skip":"you want rewards without staking."},
   {"name":"Coinbase Card","key":"coinbasecard","badge":"Best for US beginners","score":8.3,"fee":"Visa","coins":"Up to 4% in crypto","us":"US","bestfor":"Simple US spending",
    "m":[9,8,10,8,7,8,9],"pros":["Rotating crypto rewards, no staking","Instant conversion from Coinbase balance","Strong security"],"cons":["US only","Rewards rates fluctuate"],"choose":"you already use Coinbase.","skip":"you're outside the US."},
   {"name":"Bybit Card","key":"bybitcard","badge":"Best for global users","score":8.1,"fee":"Mastercard","coins":"Up to 10% (promos)","us":"EEA, UK, APAC, LATAM","bestfor":"Non-US spenders",
    "m":[8,9,8,9,9,7,7],"pros":["Low FX fees","Spend directly from trading balance","Frequent cashback promos"],"cons":["Not for US","Promo rates change"],"choose":"you're in Europe/Asia and use Bybit.","skip":"you want a stable rewards rate."},
   {"name":"Nexo Card","key":"nexo","badge":"Best credit + debit hybrid","score":8.0,"fee":"Mastercard","coins":"Up to 2% (credit) / interest (debit)","us":"EEA, UK","bestfor":"Spending without selling",
    "m":[8,8,8,8,10,8,8],"pros":["Credit mode spends against crypto collateral — no capital-gains event","Debit mode earns interest on balance","Metal card"],"cons":["Loyalty tiers require NEXO","Regional availability"],"choose":"you want to spend without selling your coins.","skip":"you dislike borrowing."},
   {"name":"Gnosis Pay","key":"gnosispay","badge":"Best self-custody card","score":7.9,"fee":"Visa","coins":"Up to 5% in GNO (with GNO holdings)","us":"EEA, UK, BR","bestfor":"Self-custody users",
    "m":[9,8,7,7,9,7,8],"pros":["Funds stay in your own Safe wallet","Spend stablecoins directly on-chain","No KYC-custodian holding your money"],"cons":["Setup is more technical","Limited regions"],"choose":"self-custody is non-negotiable.","skip":"you want an app-first experience."},
   {"name":"Wirex","key":"wirex","badge":"Best for multi-currency","score":7.6,"fee":"Visa/Mastercard","coins":"Up to 8% Cryptoback (tiers)","us":"UK, EEA, APAC","bestfor":"Travellers",
    "m":[7,8,8,8,9,7,7],"pros":["Multi-currency fiat and crypto accounts","Long-running card programme (2015)","X-tras tiers"],"cons":["Top rates need WXT staking","Mixed support reviews"],"choose":"you travel and hold several fiats.","skip":"you want the cleanest app."},
   {"name":"Binance Card (regional)","key":"binance","badge":"Best where available","score":7.4,"fee":"Visa","coins":"Up to 8% BNB (regional)","us":"Select regions","bestfor":"Binance users in supported regions",
    "m":[8,9,8,9,7,7,7],"pros":["Spend from Binance funding wallet","Low fees","High cashback in some regions"],"cons":["Withdrawn from EEA in 2023; availability varies","Check your region before applying"],"choose":"Binance offers the card in your country.","skip":"you need guaranteed availability."}
  ],
  "faq":[["Is spending crypto a taxable event?","In most countries, yes — converting crypto to pay is a disposal. Credit-mode cards (Nexo) avoid selling. Track it with a tool from our Top 7 Tax Tools."],
         ["Why do rewards keep changing?","Card rewards are marketing budgets; issuers tune them to market cycles. Treat the headline rate as a promo, not a promise."]]
 },
 "tax-tools": {
  "title":"Top 7 Crypto Tax Tools","h1":"Top 7 Crypto Tax Software (2026)",
  "desc":"The seven best crypto tax calculators for exchanges, wallets, DeFi and NFTs — scored on integrations, accuracy, country support and price.",
  "intro":"Every trade, swap, staking reward and card purchase can be a taxable event. These seven tools import your history, compute gains and export filings. Prices shown are the typical mid tier per tax year.",
  "cols":["Score","From","Integrations","Countries","Best for"],
  "items":[
   {"name":"Koinly","key":"koinly","badge":"Best overall","score":9.0,"fee":"$49–$199/yr","coins":"800+","us":"100+","bestfor":"Most users, international",
    "m":[9,8,10,10,9,8,9],"pros":["Widest exchange/wallet/chain coverage","Country-specific reports (US, UK, CA, AU, EU)","Free portfolio tracking"],"cons":["DeFi edge-cases need manual fixes","Price jumps with transaction count"],"choose":"you use multiple exchanges or live outside the US.","skip":"you have under 100 transactions — a free tier may do."},
   {"name":"CoinLedger","key":"coinledger","badge":"Best for US filers","score":8.7,"fee":"$49–$199/yr","coins":"500+","us":"US-focused + others","bestfor":"TurboTax/TaxAct users",
    "m":[8,8,10,8,8,9,9],"pros":["Direct TurboTax and TaxAct integration","Very simple flow","Responsive support"],"cons":["Less international depth","DeFi classification occasionally manual"],"choose":"you file US taxes with TurboTax.","skip":"you need non-US reports."},
   {"name":"CoinTracker","key":"cointracker","badge":"Best portfolio + tax","score":8.4,"fee":"$59–$199/yr","coins":"500+","us":"US, UK, CA, AU, IN","bestfor":"Coinbase users",
    "m":[8,7,9,9,9,8,9],"pros":["Official Coinbase and TurboTax partner","Great daily portfolio view","Mobile app"],"cons":["Pricier at higher tiers","Some chains lag"],"choose":"you want tracking all year, not just at filing.","skip":"you want the cheapest option."},
   {"name":"Crypto Tax Calculator","key":"cryptotaxcalculator","badge":"Best for DeFi & NFTs","score":8.3,"fee":"$49–$249/yr","coins":"1,000+","us":"20+","bestfor":"On-chain power users",
    "m":[8,7,8,10,10,8,8],"pros":["Deepest DeFi/NFT categorisation","Smart-contract-level parsing","MetaMask partner"],"cons":["More expensive for heavy users","Learning curve"],"choose":"your activity is mostly on-chain.","skip":"you only trade on one exchange."},
   {"name":"ZenLedger","key":"zenledger","badge":"Best for accountants","score":7.9,"fee":"$49–$399/yr","coins":"400+","us":"US-focused","bestfor":"CPA collaboration",
    "m":[8,7,8,8,8,9,8],"pros":["Tax-professional suite","Audit-trail reports","Government contracts signal rigor"],"cons":["US-centric","Interface dated"],"choose":"your accountant files for you.","skip":"you're outside the US."},
   {"name":"Blockpit","key":"accointing","badge":"Best for Europe","score":7.8,"fee":"€49–€249/yr","coins":"300+","us":"EU focus (DE, AT, FR, ES, CH…)","bestfor":"EU country-specific rules",
    "m":[8,7,8,8,8,8,8],"pros":["Country-specific EU tax logic (e.g., German 1-year rule)","Acquired Accointing","Optimisation hints"],"cons":["Thinner outside Europe","Fewer DeFi integrations"],"choose":"you file in the EU.","skip":"you're a US filer."},
   {"name":"TokenTax","key":"tokentax","badge":"Best full-service","score":7.5,"fee":"$65–$3,499/yr","coins":"300+","us":"US + intl","bestfor":"Complex cases, done-for-you",
    "m":[8,5,8,8,9,10,8],"pros":["Software plus in-house CPAs","Handles margin, DeFi, NFTs and reconciliation","Audit support"],"cons":["Expensive at the top","Overkill for simple portfolios"],"choose":"your situation is complicated.","skip":"you have a simple portfolio."}
  ],
  "faq":[["Do I need tax software?","If you made more than a handful of transactions, yes — manual cost-basis tracking across exchanges is where most filing errors come from."],
         ["Which cost-basis method should I use?","Depends on your country; many allow FIFO and specific-ID. The tools above let you compare methods before you file — pick the one allowed in your jurisdiction that minimises tax."]]
 }
}
